<template>
<div id="app">
	<vue-progress-bar></vue-progress-bar>
	<transition name="modal-animation">
		<modal v-if="modalData" :data="modalData"></modal>
	</transition>
	<nav-bar>
		<router-link to="/" exact>Home</router-link>
		<router-link to="/search/images">Search</router-link>
		<router-link to="/upload" exact>Upload</router-link>
	</nav-bar>
	<div class="body-wrapper">
		<transition name="fade" mode="out-in">
			<router-view></router-view>
		</transition>
	</div>
	<footer>
		&copy; Brussell 2017 &nbsp;|&nbsp; <a href="mailto:brusselldesu@gmail.com" target="_blank">Contact</a><br>
		Made with <a href="https://vuejs.org/" target="_blank">vuejs</a>. No Bootstrap, no jQuery. <a href="/api-docs" target="_blank">API docs here</a>
	</footer>
</div>
</template>

<script>
export default {
	data() {
		return {
			modalData: null
		};
	},
	beforeMount() {
		this.$store.dispatch('getSelf');
	},
	mounted() {
		// When App.vue is finish loading finish the progress bar
		this.$Progress.finish();
	},
	created() {
		// When App.vue is first loaded start the progress bar
		this.$Progress.start();
		// hook the progress bar to start before we move router-view
		this.$router.beforeEach((to, from, next) => {
			// start the progress bar
			this.$Progress.start();
			next();
		});
		// hook the progress bar to finish after we've finished moving router-view
		this.$router.afterEach((to, from) => {
			this.$Progress.finish();
		});

		if (this.$store.state.lastUpdateMessage !== 'beta2') {
			this.$data.modalData = {
				title: 'Account registration open!',
				body: "After initial testing, wa are now ready to open up the site to everyone. Once you have an account you can begin uploading images, but make sure you read the guidelines first! If you encounter any issues you can report them at <a href=\"https://github.com/brussell98/catgirls-website\" target=\"_blank\">the GitHub repo</a>"
			};
			this.$store.commit('lastUpdateMessage', 'beta2');
		}
	}
}
</script>

<style lang="sass">
*, *:before, *:after
	box-sizing: border-box

html
	font-size: 100%

a
	color: #4ACFFF
	text-decoration: none
	&:hover, &:active, &:focus
		color: darken(#4ACFFF, 15)
		text-decoration: underline

.btn
	padding: 5px 10px
	cursor: pointer
	font-family: 'Nunito', sans-serif
	font-size: 1.25rem
	color: #FFF
	background-color: #2DE58C
	box-shadow: 0 0 3px rgba(#2DE58C, .4)
	border: none
	border-radius: 3px
	transition: background .3s
	&:hover, &:focus
		background: darken(#2DE58C, 15)
	&.warn
		background-color: #FDD835
		&:hover, &:focus
			background: darken(#FDD835, 15)
	&.danger
		background-color: #E53935
		&:hover, &:focus
			background: darken(#E53935, 15)

#app
	font-family: 'Nunito', sans-serif
	max-width: 1280px
	margin: auto
	margin-top: 2rem
	.fade-enter-active, .fade-leave-active
		transition: all .2s ease
	.fade-enter, .fade-leave-active
		opacity: 0
	.modal-animation-enter-active, .modal-animation-leave-active
		transition: all .6s ease-in-out
		.modal, .header
			transition: all .6s ease-in-out
	.modal-animation-enter, .modal-animation-leave-active
		opacity: 0
		.modal, .header
			transform: translateY(-100px)
	.body-wrapper
		box-shadow: 0 0 3px #CCC
		margin-top: 1rem
		border-radius: .25rem
		padding: 1rem 2rem
	#base
		.error
			color: #A22

footer
	text-align: center
	color: #777
	font-family: 'Nunito', sans-serif
	margin-top: 1rem


// * Generated by Animista
// * http://animista.net

// * animation slide-in-fwd-center
@keyframes slide-in-fwd-center
	0%
		transform: scale(0)
		opacity: 0
	100%
		transform: scale(1)
		opacity: 1

// * animation slide-out-bck-center
@keyframes slide-out-bck-center
	0%
		transform: scale(1)
		opacity: 1
	100%
		transform: scale(0)
		opacity: 0

</style>
