<template>
<div id="app">
	<vue-progress-bar></vue-progress-bar>
	<nav-bar>
		<router-link to="/" exact>Home</router-link>
		<router-link to="/search/images">Search</router-link>
		<router-link to="/upload" exact>Upload</router-link>
	</nav-bar>
	<div class="body-wrapper">
		<transition name="fade" mode="out-in">
			<router-view></router-view>
		</transition>
	</div>
	<footer>
		&copy; Brussell 2017 &nbsp;|&nbsp; <a href="mailto:brusselldesu@gmail.com" target="_blank">Contact</a><br>
		Made with <a href="https://vuejs.org/" target="_blank">vuejs</a>. No Bootstrap, no jQuery. <a href="/api-docs/index.html" target="_blank">API docs here</a>
	</footer>
</div>
</template>

<script>
export default {
	data() {
		return { };
	},
	beforeMount() {
		this.$store.dispatch('getSelf');
	},
	mounted() {
		// When App.vue is finish loading finish the progress bar
		this.$Progress.finish();
	},
	created() {
		// When App.vue is first loaded start the progress bar
		this.$Progress.start();
		// hook the progress bar to start before we move router-view
		this.$router.beforeEach((to, from, next) => {
			// start the progress bar
			this.$Progress.start();
			next();
		});
		// hook the progress bar to finish after we've finished moving router-view
		this.$router.afterEach((to, from) => {
			this.$Progress.finish();
		});

		if (this.$store.state.lastUpdateMessage !== 'beta4') {
			this.$Modal.info({
				title: 'New Update!',
				content: "It's finally here! The site has been updated with a new UI using iview. With this re-design comes many quality of life improvements around the site. One of these is the ability to search images by upload date. Go ahead and browse around to see everything that's changed!"
			});
			this.$store.commit('lastUpdateMessage', 'beta4');
		}
	}
}
</script>

<style lang="sass">

body
	font-size: 100%

#app
	font-family: 'Nunito', sans-serif
	max-width: 1280px
	margin: auto
	margin-top: 2rem
	.fade-enter-active, .fade-leave-active
		transition: all .2s ease
	.fade-enter, .fade-leave-active
		opacity: 0
	.body-wrapper
		box-shadow: 0 0 3px #CCC
		margin-top: 1rem
		border-radius: .25rem
		padding: 1rem 2rem

footer
	text-align: center
	color: #777
	font-family: 'Nunito', sans-serif
	margin: 1rem 0

.page-wrapper
	margin-top: 10px
	margin-bottom: 10px
	height: 32px

.ivu-btn
	font-size: 1rem

.ivu-form .ivu-form-item-label
	font-size: 14px

// * Generated by Animista
// * http://animista.net

// * animation slide-in-fwd-center
@keyframes slide-in-fwd-center
	0%
		transform: scale(0)
		opacity: 0
	100%
		transform: scale(1)
		opacity: 1

// * animation slide-out-bck-center
@keyframes slide-out-bck-center
	0%
		transform: scale(1)
		opacity: 1
	100%
		transform: scale(0)
		opacity: 0

</style>
